### ISSUE TITLE
affinity not attributed to player (or to correct player)

### ISSUE THREAD

**Issue by synrg** [JeannotM/DynamicDifficulty#10]
After passing our initial evaluation, we decided to enable this plugin on our main server. Initially, one player joined and played for a bit. I checked their points about 40 minutes later and they were at 934. Given how many mobs they had killed since the beginning, that seemed about right.

A second player then joined, I noted their points after just a couple of minutes (937) and then continued to watch both players over the next half hour. The second player's point's continued to increase over time, finally reaching 1452 before we discontinued using the plugin, while the 1st player's points never went up again! The affinity score remained at 934.

All of this continued to happen even while the 2nd player was taking a break and not interacting much at all (but remained online). Is it possible all of the affinity points are simply getting added to the last player in the file?

We're using the default storage (file) if it makes any difference.

The plugin is disabled for now until we can sort this out. It seems we need some logging in order to know for sure what's going on, but I haven't time to do a more detailed analysis at this time. I'd be happy to help, though, if you could provide me with instructions, (up to and including insertion of appropriate debug logging / rebuilding the plugin locally, if that's what it takes).

**Comment by synrg** [comment]
This morning, I had the same 2 players join a test server with identical settings but different world, and we couldn't reproduce people's points not changing there.

Then we went back and re-enabled the plugin on the main server and again couldn't reproduce points failing to change when they should've been changing.

So for now, I instructed them to self-monitor their points with `/dd get` and have asked all other players to do the same. I'll update the issue if we have a recurrence of the issue.

**Comment by JeannotM** [comment]
Thanks for looking into this, I tried it once for a short time, but also didn't have any issues regarding it. I think it may occured of an error whilst joining, but don't have any evidence to support that claim any further

**Comment by synrg** [comment]
The odd thing, if it was an error while joining, is we'd have to explain why it happened twice in succession from a single server start, but on the next restart it has never happened again. So maybe the failure condition is when the plugin loads? I can't think what, though.
