### ISSUE TITLE
The onMined block (BlockBreakEvent) didn't add affinity to the player

### ISSUE THREAD

**Issue by dsx137** [JeannotM/DynamicDifficulty#15]
Is it a bug?

Additionally, there will be an extra material after i mine the block(ore).

server: paper-1.20.1-20.jar
plugin version: 1.6b and 1.7 (both have this problem)
at BlockMinedListener.java `onMined()`

A Bukkit multithread (maybe? i haven't learned that) is created for adding affinity.
But run to the code, the block has been broken, so `e.getBlock().getType()` is null.

So i modify the code as this: 

```java
@EventHandler(priority = EventPriority.HIGHEST)
    public void onMined(BlockBreakEvent e) {
        if(!MAIN_MANAGER.getPlayerManager().isPlayerValid(e.getPlayer())) return;
        ItemStack tool = e.getPlayer().getInventory().getItemInMainHand();
        Material type = e.getBlock().getType();
        if (tool == null) return;
        Bukkit.getScheduler().runTask(MAIN_MANAGER.getPlugin(), () -> {
            if(BLOCKS.size() == 0) return;

            if(BLOCKS.containsKey(type))
                if(silkTouchAllowed || ! tool.containsEnchantment(Enchantment.SILK_TOUCH))
                    MAIN_MANAGER.getPlayerManager().addAffinity(e.getPlayer().getUniqueId(), BLOCKS.get(type));
        });

//        if (ORE_BLOCKS.containsKey(e.getBlock().getType())) {
//            if (! tool.containsEnchantment(Enchantment.SILK_TOUCH))
//                e.getPlayer().getWorld().dropItemNaturally(e.getBlock().getLocation(),
//                        new ItemStack(ORE_BLOCKS.get(e.getBlock().getType())));
//        }
    }
```

So that it can work correctly.

**Comment by dsx137** [comment]
`e.getPlayer().getItemInUse()` is also null, so i alternative it into `e.getPlayer().getInventory().getItemInMainHand()`.
I don't know how.

**Comment by JeannotM** [comment]
Thanks, for bringing this to my attention, this has been fixed in the latest update. Thanks again and have a nice day!
