### ISSUE TITLE
[Bug] Double-loot-chance with 0 value always makes coal, emerald, diamond, and possibly redstone and lapis ores to be double drop

### ISSUE THREAD

**Issue by noiverre** [JeannotM/DynamicDifficulty#16]
Version: v1.7
Plugins: ![image](https://github.com/JeannotM/DynamicDifficulty/assets/77881970/100153b9-ca94-4617-93f7-03a34b107fcd)
![image](https://github.com/JeannotM/DynamicDifficulty/assets/77881970/e75a932a-f338-4e34-b812-10b7d419611f)

**Comment by JeannotM** [comment]
This was fixed in the newest release on Spigot, sorry for the mistake xd and thanks for reporting this!
Have a nice day!
