### ISSUE TITLE
[Not Issue]Ask permission for Translate & Transport this Plugin to a Chinese Forum

### ISSUE THREAD

**Issue by kuzuanpa** [JeannotM/DynamicDifficulty#2]
//Sorry to bother you in there.There is a firewall in Chinese Mainland that blocked Discord so i can only ask for permission for transport in there

Hi! I've use this plugins and think it is really a good plugin!
I want to translate the plugin to Chinese and release it in MCBBS(a Chinese minecraft forum) to let more players know it!
er..I won't mark it as my original creation and I'll put the spigotmc.org download link in my page that every server owners can only download the plugin trough it.

**Comment by JeannotM** [comment]
Yeah, I'm fine with that. But, I have something almost ready if you'd like to add you're own translations in the plugin itself

**Comment by kuzuanpa** [comment]
thanks a lot and I've noticed the lang.yml 
In fact I will translate not only the messages but also notes
