### ISSUE TITLE
[bug]Player will drop xp_orb when die with keep-inventory is true

### ISSUE THREAD

**Issue by kuzuanpa** [JeannotM/DynamicDifficulty#3]
Player will drop xp_orb when die with keep-inventory is true.
I configured a difficulty called Baby with keep-inventory is true, and I found when Player died in this difficulty , they will drop xp_orb with their xp level isn't changed.They can make many xp using this bug.without

**Comment by JeannotM** [comment]
Thanks for bringing this to my attention, I'll be fixing it soon

**Comment by JeannotM** [comment]
Hey Kuzuanpa, I've added Multilanguage support. So if you'd like you can add your own translation to the lang file via Pull Request. That way more people will have access to a language they can understand.

If you're interested you can follow this video: https://youtu.be/nT8KGYVurIU?t=146 (I can also send over text instructions if you're more comfortable with that)

I've also fixed the issue you described here, so I'll be closing this PR soon. Thanks for messaging the issue to me!

**Comment by kuzuanpa** [comment]
I've modify my translate and created a pull request just now. and thanks for resolve this bug!

**Comment by MoeShimaKaze** [comment]
This bug still exists in the latest version.
