### ISSUE TITLE
affinity reduced even though player killed by a fall

### ISSUE THREAD

**Issue by synrg** [JeannotM/DynamicDifficulty#9]
A player joined, had two deaths from falls, and left. Their final affinity had 200 points deducted from the default affinity 600 for a final score in data.json of 400. Any idea what's up?

We have DynamicDifficulty v1.6 installed on Paper version git-paper-160 (MC: 1.19.2) with mostly default settings for DynamicDifficulty (just a few percentages changed, and no toggles touched).

relevant settings from our config.yml:

```yml
death: -100
starting-affinity: 600
toggle-settings:
  difficulty-type: player
  prevent-affinity-loss-on-suicide: true
```

Java is not a language I use on a regular basis, and I'm not at all familiar with Spigot API or your code, so am not entirely confident of my reading of how it ought to work, but checked out both the code and the relevant Spigot API doc and found:

- when the `onDeath()` handler fires, it should receive from `e.getEntity().getLastDamageCause()` an `EntityDamageEvent`
  - the `EntityDamageEvent` implements a `DamageCause` interface (nested class) so provides the Enum that we check next
- the cause should've been `DamageCause.FALL`, according to the "... fell from a high place" message found in the log
- that cause should've therefore been matched because it is included in `COUNTS_AS_SUICIDE`
- so the handler should've bailed at the `return` statement, skipping `addAffinity()` for the `onDeath` amount

However, the evidence from `data.json` for this player indicates otherwise. I double-checked and yes, the affinity unmistakably belongs to the player who fell from a high place and not anyone else (I'm the only other player who joined, and my affinity is just above 600 ... and the uuid and name for their stanza is a match).

**Comment by synrg** [comment]
Confirmed in latest Paper version git-paper-179 by checking my own affinity, upgrading, restarting the server, joining, then killing myself with a FALL, then checking affinity afterwards. -100 adjustment was applied for the fall, and the server message for my death was "fell from a high place".

**Comment by synrg** [comment]
Don't you have to do a `.getCause()` on the event to get the cause? Otherwise you're testing if the *event* is included in the `EnumSet`, not the *cause* itself, which is why the comparison fails.

**Comment by JeannotM** [comment]
Thank you for such a detailed analysis. Thanks to you I can probably fix this in a few minutes, but I'll try to look later in the week when I have some time off to also work on other bugs

**Comment by JeannotM** [comment]
This has been fixed in an earlier commit and will be shipped when the next version releases. Thank you for the detailed analysis
